name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/second_lab

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}

    - name: Run Docker container
      run: |
        docker run -d --name testcontainer ${{ steps.meta.outputs.tags }}     

    - name: Run unit tests
      run: |
        docker exec testcontainer python -m unittest tests/test_app.py

    - name: Run integration tests
      run: |
        docker exec testcontainer python tests/integration_test.py

    - name: Remove Docker container
      run: docker rm -f testcontainer

    - name: Push Docker image
      run: docker push ${{ steps.meta.outputs.tags }}